# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Set-DisplayResolution -Width 1920 -Height 1080 -Force'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/junitreports/TEST-*.xml'
    goals: 'clean test -PDemoADOIntegration'
- script: 
   echo "$(Pipeline.Workspace)"
- task: PublishPipelineArtifact@1
  inputs:
      targetPath: 'Reports'
      artifact: 'Extent Reports'
      publishLocation: 'pipeline'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'ScreenShots'
    artifact: 'ScreenShots'
    publishLocation: 'pipeline'